import p2_img from "./product_2.jpg";
import p4_img from "./product_4.jpg";
import p6_img from "./product_6.jpg";
import p8_img from "./product_8.jpg";
import p10_img from "./product_10.jpg";
import p12_img from "./product_12.jpg";
import p14_img from "./product_14.jpg";
import p16_img from "./product_16.jpg";
import p18_img from "./product_18.jpg";
import p20_img from "./product_20.jpg";
import p22_img from "./product_22.jpg";
import p24_img from "./product_24.jpg";
import p26_img from "./product_26.jpg";
import p27_img from "./product_27.jpg";
import p28_img from "./product_28.jpg";
import p30_img from "./product_30.jpg";
import p32_img from "./product_32.jpg";
import p35_img from "./product_35.jpg";

let all_product = [
  {
    id: 1,
    name: "Short Skirt One Piece Perfect Sleeves and Neck Cut",
    category: "women",
    image: p1_img,
    new_price: 50.0,
    old_price: 80.5,
  },
  {
    id: 2,
    name: "Short Skirt One Piece Perfect Sleeves and Neck Cut",
    category: "women",
    image: p2_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 3,
    name: "Short Skirt One Piece Perfect Sleeves and Neck Cut",
    category: "women",
    image: p3_img,
    new_price: 60.0,
    old_price: 100.5,
  },
  {
    id: 4,
    name: "Short Skirt One Piece Perfect Sleeves and Neck Cut",
    category: "women",
    image: p4_img,
    new_price: 100.0,
    old_price: 150.0,
  },
  {
    id: 5,
    name: "Short Skirt One Piece Perfect Sleeves and Neck Cut",
    category: "women",
    image: p5_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 6,
    name: "Short Skirt One Piece Perfect Sleeves and Neck Cut",
    category: "women",
    image: p6_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 7,
    name: "Short Skirt One Piece Perfect Sleeves and Neck Cut",
    category: "women",
    image: p7_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 8,
    name: "Short Skirt One Piece Perfect Sleeves and Neck Cut",
    category: "women",
    image: p8_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 9,
    name: "Short Skirt One Piece Perfect Sleeves and Neck Cut",
    category: "women",
    image: p9_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 10,
    name: "Short Skirt One Piece Perfect Sleeves and Neck Cut",
    category: "women",
    image: p10_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 11,
    name: "Short Skirt One Piece Perfect Sleeves and Neck Cut",
    category: "women",
    image: p11_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 12,
    name: "Short Skirt One Piece Perfect Sleeves and Neck Cut",
    category: "women",
    image: p12_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 13,
    name: "Perfect Fit Coat Shirt Pant Good Quality Fabric",
    category: "men",
    image: p13_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 14,
    name: "Perfect Fit Coat Shirt Pant Good Quality Fabric",
    category: "men",
    image: p14_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 15,
    name: "Perfect Fit Coat Shirt Pant Good Quality Fabric",
    category: "men",
    image: p15_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 16,
    name: "Perfect Fit Coat Shirt Pant Good Quality Fabric",
    category: "men",
    image: p16_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 17,
    name: "Perfect Fit Coat Shirt Pant Good Quality Fabric",
    category: "men",
    image: p17_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 18,
    name: "Perfect Fit Coat Shirt Pant Good Quality Fabric",
    category: "men",
    image: p18_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 19,
    name: "Perfect Fit Coat Shirt Pant Good Quality Fabric",
    category: "men",
    image: p19_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 20,
    name: "Perfect Fit Coat Shirt Pant Good Quality Fabric",
    category: "men",
    image: p20_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 21,
    name: "Perfect Fit Coat Shirt Pant Good Quality Fabric",
    category: "men",
    image: p21_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 22,
    name: "Perfect Fit Coat Shirt Pant Good Quality Fabric",
    category: "men",
    image: p22_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 23,
    name: "Perfect Fit Coat Shirt Pant Good Quality Fabric",
    category: "men",
    image: p23_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 24,
    name: "Perfect Fit Coat Shirt Pant Good Quality Fabric",
    category: "men",
    image: p24_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 25,
    name: "Good Quality Kids Shirt Pant and Skirt Perfect Sizes",
    category: "kid",
    image: p25_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 26,
    name: "Good Quality Kids Shirt Pant and Skirt Perfect Sizes",
    category: "kid",
    image: p26_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 27,
    name: "Good Quality Kids Shirt Pant and Skirt Perfect Sizes",
    category: "kid",
    image: p27_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 28,
    name: "Good Quality Kids Shirt Pant and Skirt Perfect Sizes",
    category: "kid",
    image: p28_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 29,
    name: "Good Quality Kids Shirt Pant and Skirt Perfect Sizes",
    category: "kid",
    image: p29_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 30,
    name: "Good Quality Kids Shirt Pant and Skirt Perfect Sizes",
    category: "kid",
    image: p30_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 31,
    name: "Good Quality Kids Shirt Pant and Skirt Perfect Sizes",
    category: "kid",
    image: p31_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 32,
    name: "Good Quality Kids Shirt Pant and Skirt Perfect Sizes",
    category: "kid",
    image: p32_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 33,
    name: "Good Quality Kids Shirt Pant and Skirt Perfect Sizes",
    category: "kid",
    image: p33_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 34,
    name: "Good Quality Kids Shirt Pant and Skirt Perfect Sizes",
    category: "kid",
    image: p34_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 35,
    name: "Good Quality Kids Shirt Pant and Skirt Perfect Sizes",
    category: "kid",
    image: p35_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 36,
    name: "Good Quality Kids Shirt Pant and Skirt Perfect Sizes",
    category: "kid",
    image: p36_img,
    new_price: 85.0,
    old_price: 120.5,
  },
];

export default all_product;
